jobs:
  - name: runsh-job-pubparam
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-pubparam
      - TASK:
        - script: IN/sample-pub/gitRepo/echo.sh
    flags: job1param
    
  - name: runcliscript-job-pubparam
    type: runCLI
    allowPublicAccess: true
    steps:      
      - IN: sample-scriptpvtparam
      - TASK:
        - script: IN/sample-scriptpvt/gitRepo/echo.sh
    flags: job-runcliparam
        
        
  - name: manifest_dep_pubparam
    type: manifest
    allowPublicAccess: true
    steps:
      - IN: sample_img_pubparam
    flags: manifestparam

  - name: sample_publicrepo_runCI
    type: runCI
    allowPublicAccess: true
    steps:
      - IN: sample_publicrepo_ciRepo
      - IN: ar-paramsUserDefinedpub
    flags:
      - sample_publicrepo_runCIparam
      - sample_publicrepo_runCIEnabledFromCIbutAddedFlagsInJobsYmlparam      
      
  - name: sample-release-pubparam
    type: release
    allowPublicAccess: true
    steps:
      - IN: sample-version-pubparam
      - TASK: managed
        bump: rc

  - name: runsh-param1-pub
    type: runSh
    steps:
      - IN: test_params1pub
      - TASK:
        - script: echo "A=$A"
        - script: echo "B=$B"
        - script: echo "p1=$p1"
        - script: echo "p2=$p2"
  
  - name: runsh-param2-pub
    type: runSh
    steps:
      - IN: test_params2pub
      - TASK:
        - script: echo "foo=$foo"
        - script: echo "boo=$boo"
        - script: echo "p3=$p3"
        - script: echo "p4=$p4"
  
  - name: runsh-param3-pub
    type: runSh
    steps:
      - IN: test_params3pub
      - IN: runsh-param2-pub
      - TASK:
        - script: echo "foo=$foo"
        - script: echo "boo=$boo"
        - script: echo "p3=$p3"
        - script: echo "p4=$p4"
        - script: echo "p5=$p5"
        - script: echo "p6=$p6"
        
  - name: runsh-param1234-pub
    type: runSh
    steps:
      - IN: test_params1pub
      - IN: test_params2pub
      - IN: test_params3pub
      - IN: test_params4pub
      - TASK:
        - script: echo "A=$A"
        - script: echo "B=$B"
        - script: echo "p1=$p1"
        - script: echo "p2=$p2"
        - script: echo "foo=$foo"
        - script: echo "boo=$boo"
        - script: echo "p3=$p3"
        - script: echo "p4=$p4"
        - script: echo "p5=$p5"
        - script: echo "p6=$p6"  
        - script: echo "p7=$p7"
        - script: echo "p8=$p8"
        